sudo: false
language: node_js
node_js:
  - "10.16.1"
env:
  - CXX=g++-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
script:
  - npm test
  - npm run build
branches:
  except: 
    - gh-pages
deploy:
  - provider: npm
    skip_cleanup: true
    email: "reto@factsmission.com"
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: distribution/latest/rdf2h.js
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash .travis_publish
    on:
      tags: true
